apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: app-tier-ns
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "update", "list", "delete", "create"]

