apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-role
subjects:
- kind: User
  name: myuser
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

